name: Shanghai Ruby User Group
markdown: redcarpet
pygments: true
timezone: Asia/Shanghai
keep_files:  ['.git']
site: http://shruby.github.io
url: http://shruby.github.io
description: 'Web site of ShRuby.github.io'